# ***Torch Basics***

In [1]:
import torch
import numpy as np

### Creating Tensors

Tensors can be created using the below methods.

- ones
- empty
- rand
- from numpy

#### Using ones with 1d tensors:

In [2]:
torch.ones(1)

tensor([1.])

#### Using ones with 2d tensors:

In [3]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

#### Using empty():

In [4]:
torch.empty(2, 2)

tensor([[1.0175e+16, 3.0917e-41],
        [1.0237e+16, 3.0917e-41]])

#### Using rand():

In [5]:
torch.rand(2, 2)

tensor([[0.5898, 0.4683],
        [0.8112, 0.4522]])

#### Using from_numpy()

In [6]:
arr = np.array([1,2,3])
torch.from_numpy(arr)

tensor([1, 2, 3])

## Autograd

To keep track of a variable and to create computational graph we need to use 'requires_grad' to be True

In [7]:
x = torch.ones(3, requires_grad=True)
x

tensor([1., 1., 1.], requires_grad=True)

In [8]:
y = x + 2
y

tensor([3., 3., 3.], grad_fn=<AddBackward0>)

##### *Note: 
- The grad_fn will be created for the calculation of y = x + 2. we use backward() to calculate the gradients of x later.

In [9]:
y = y.mean()
y.backward()
print(f'x.grad = {x.grad.sum().item()}')
x.grad.zero_()
print()

x.grad = 1.0



#### *Note: 
- The backward() calculates dy/dx and x.grad.sum() is required as it splits to 3 elements.
- x.grad.zero_() is required to avoid accumulating the grads into x.grad